version: '3.7'

services:
  server:
    image: "karlglans/cro:0.0.1"
    container_name: cro_local
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - '5005:5005'
      - '8081:8080'
      - '35729:35729'
    environment:
      - jar_name=croc-0.0.1-SNAPSHOT.jar
    depends_on:
      - crodb
    links:
      - crodb
  crodb:
    image: postgres:9
    restart: always
    environment:
    - POSTGRES_PASSWORD=example
    - POSTGRES_USER=postgres
    - POSTGRES_DB=croc
#  adminer:
#    depends_on:
#    - crodb
#    image: adminer
#    restart: always
#    ports:
#    - 8082:8080

